feat: changing cycles to discount in subscriptions and plans
pagarme/ecommerce-module-core pull request #108
Opened 2023-09-14 13:12 UTC by mateus-picoloto

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-575
| **What?**         | Changing cycles to discount in subscriptions and plans.
| **Why?**          | To be able to apply discount in all charges from subscriptions and plans.
| **How?**          | Changing cycles to discount in subscriptions and plans.

2023-09-15 01:31 UTC, mauriciohaygert approved these changes

2023-09-15 14:32 UTC, RafaMelazzo requested changes

2023-09-15 14:32 UTC, RafaMelazzo commented on src/Recurrence/Aggregates/Plan.php
> +    private $applyProductsCycleToDiscount;
$applyDiscountInAllProductCycles

2023-09-15 14:32 UTC, RafaMelazzo commented on src/Recurrence/Aggregates/Plan.php
> +    public function getApplyProductsCycleToDiscount()
getApplyDiscountInAllProductCycles

2023-09-15 14:32 UTC, RafaMelazzo commented on src/Recurrence/Aggregates/Plan.php
> +    public function setApplyProductsCycleToDiscount($applyProductsCycleToDiscount)
setApplyDiscountInAllProductCycles

2023-09-15 17:50 UTC, RafaMelazzo submitted a review, later dismissed

2023-09-15 17:52 UTC, fabiano-mallmann commented on src/Recurrence/Aggregates/Repetition.php
> +            ($this->getInterval() === $repetitionObject->getInterval()) &&
Os parenteses não fazem sentido existirem e adicionar os "agregadores" segundo as PERs.

2023-09-15 18:12 UTC, mateus-picoloto commented on src/Recurrence/Aggregates/Repetition.php
> +            ($this->getInterval() === $repetitionObject->getInterval()) &&
Ajustado

2023-09-18 12:12 UTC, RafaMelazzo approved these changes

2023-09-19 14:32 UTC, fabiano-mallmann approved these changes

2023-09-19 18:51 UTC, merged