feat: added new fields to recipient
pagarme/ecommerce-module-core pull request #149
Opened 2024-03-22 18:52 UTC by fabiano-mallmann

![Git Merge](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **develop**.

### Qual o tipo de PR é esse? (marque todos os aplicáveis)
- [ ] Refatoração
- [x] Adição de funcionalidade
- [ ] Correção de bug
- [ ] Otimização
- [ ] Atualização de documentação

### Descrição
Adicionado novas campos no cadastro de recebedores para atender a determinação do Bacen.

### Cenários testados
Cadastro de novos recebedores PF e PJ, com novas informações, e também buscando dados de recebedores já cadastrados na Dash do Pagar.me (cenário de recebedor antigo, já que a Dash ainda não recebeu essa atualização)

2024-03-25 19:48 UTC, RafaMelazzo requested changes

2024-03-25 19:48 UTC, RafaMelazzo commented on src/Middle/Model/Phones.php
> +        return sprintf("%05s", $phone);
Esse `sprintf` é necessário?

2024-03-25 19:48 UTC, RafaMelazzo commented on src/Middle/Model/Recipient.php
> +    }
Remover função

2024-03-25 19:48 UTC, RafaMelazzo commented on src/Middle/Model/Recipient.php
> +use PagarmeCoreApiLib\Models\UpdateRecipientRequest;
Remover

2024-03-25 19:48 UTC, RafaMelazzo commented on src/Middle/Proxy/RecipientProxy.php
> +    }
Remover função

2024-03-25 19:52 UTC, mateus-picoloto requested changes

2024-03-25 19:52 UTC, mateus-picoloto commented on src/Middle/Interfaces/BaseRecipientInterface.php
> +interface BaseRecipientInterface
Essa interface não tem nenhum método a ser implementado

2024-03-25 19:52 UTC, mateus-picoloto commented on src/Middle/Model/Recipient.php
> +    public function convertToUpdateRequest()
Vale a pena adicionar método que não vai ser usado ainda?

2024-03-25 19:52 UTC, mateus-picoloto commented on src/Middle/Proxy/RecipientProxy.php
> +    public function updateRecipient(BaseRecipientInterface $recipient)
Vale a pena adicionar método que não vai ser usado ainda?

2024-03-26 13:18 UTC, fabiano-mallmann commented on src/Middle/Model/Phones.php
> +        $phone = preg_replace('/(?!\d)./', '', $phoneNumber);
Feito

2024-03-26 13:18 UTC, fabiano-mallmann commented on src/Middle/Model/Phones.php
> +        return sprintf("%05s", $phone);
Removido

2024-03-26 13:19 UTC, fabiano-mallmann commented on src/Middle/Model/Recipient.php
> +    }
Removido

2024-03-26 13:19 UTC, fabiano-mallmann commented on src/Middle/Model/Recipient.php
> +use PagarmeCoreApiLib\Models\UpdateRecipientRequest;
Removido

2024-03-26 13:20 UTC, fabiano-mallmann commented on src/Middle/Proxy/RecipientProxy.php
> +    }
Removido

2024-03-26 13:20 UTC, fabiano-mallmann commented on src/Middle/Model/Recipient.php
> +    public function convertToUpdateRequest()
Removido

2024-03-26 13:20 UTC, fabiano-mallmann commented on src/Middle/Proxy/RecipientProxy.php
> +    public function updateRecipient(BaseRecipientInterface $recipient)
Removido

2024-03-26 14:06 UTC, fabiano-mallmann commented on src/Middle/Interfaces/BaseRecipientInterface.php
> +interface BaseRecipientInterface
Removi a interface pois ela seria apenas um 'alias' para o arquivo src/Middle/Model/Marketplace/BaseRegisterInformation.php

2024-03-26 14:06 UTC, fabiano-mallmann commented on src/Middle/Interfaces/BaseRecipientInterface.php
> +interface BaseRecipientInterface
Removi a interface pois ela seria apenas um 'alias' para o arquivo src/Middle/Model/Marketplace/BaseRegisterInformation.php

2024-03-26 14:13 UTC, mateus-picoloto approved these changes

2024-03-26 19:42 UTC, RafaMelazzo approved these changes

2024-03-26 20:55 UTC, merged