Changes from mundipagg repo
pagarme/ecommerce-module-core pull request #3
Opened 2021-04-27 17:57 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **What?**         | This PR brings changes that were implemented in the mundipagg repository.

2021-04-27 21:54 UTC, vberardi requested changes

2021-04-27 21:54 UTC, vberardi commented on src/Kernel/Services/OrderService.php
> +    public function getOrderByMundiPaggId(OrderId $orderId)
Aqui precisamos manter "**getOrderByPagarmeId**()".

2021-04-27 23:50 UTC, willian-soaresferreira requested changes

2021-04-27 23:50 UTC, willian-soaresferreira commented on src/Kernel/Services/OrderService.php
> +            //Send through the APIService to mundipagg
~~mundipagg~~ -> Pagarme

2021-04-27 23:50 UTC, willian-soaresferreira commented on src/Kernel/Services/OrderService.php
> +    private function responseHasChargesAndFailed($response)
Pode trocar o nome do método por favor, para _responseHasNoChargesOrFailed_, eu reparei posteriormente em uma outra tarefa minha (que ainda está em andamento), conversei com o @netorodrigues e combinei até que eu traria para a Pagar.me, mas como você já ficou nessa missão de trazer as alterações recentes, pode mudar por favor :)

2021-04-28 13:32 UTC, vberardi approved these changes

2021-04-28 15:19 UTC, willian-soaresferreira requested changes

2021-04-28 15:19 UTC, willian-soaresferreira commented on src/Kernel/Services/OrderService.php
> +        if ($this->responseHasChargesAndFailed($response)) {
Faltou só trocar o nome método aqui onde é utilizado também (para `responseHasNoChargesOrFailed`).

2021-04-28 17:11 UTC, willian-soaresferreira approved these changes

2021-04-28 17:50 UTC, vberardi approved these changes

2021-04-28 20:18 UTC, merged