[Feature] Adds Hub environment info
pagarme/ecommerce-module-core pull request #7
Opened 2021-06-14 22:32 UTC by vberardi

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-165
| **What?**         | Adds Hub environment info
| **Why?**          | To show the Hub's environment integrated
| **How?**          | Saving the type returned by Hub's API

#### :package: Attachments
![hub_environment](https://user-images.githubusercontent.com/916822/121967008-f8784080-cd45-11eb-9d44-808d99e9a78b.jpg)

2021-06-16 15:19 UTC, willian-soaresferreira requested changes
Opa Vini, em geral me parece ok, mas precisamos criar testes pelo menos para os pontos que sofreram alteração, se não existir algum teste do método atualmente, a gente cria. 

No caso de alterações de url por exemplo, até tudo bem não criar o teste para o método por ora, mas para os métodos `setHubEnvironment` e `createFromStdClass`, é importante criar e testar por exemplo se o environment setado é retornado no getter, e se ao enviar o environment _Sandbox_ ou _Development_ retornará a classe de chave de teste, e em caso de _Production_ retornará uma classe de chave de live.

Isso nos dá mais segurança em futuras alterações.

2021-06-16 19:35 UTC, netorodrigues commented on src/Kernel/Factories/ConfigurationFactory.php
> +            $config->setHubEnvironment($data->hubEnvironment);
Nesse if a gente verifica a existência do `hubInstallId`, mas assume que não só o `hubInstallId` existe no `$data`. Acho que vale a pena a gente fazer um if separado pra verificar a existência do `hubEnvironment`, até pra seguir o padrão do método.

2021-06-16 19:35 UTC, netorodrigues approved these changes

2021-06-17 16:10 UTC, vberardi commented on src/Kernel/Factories/ConfigurationFactory.php
> +            $config->setHubEnvironment($data->hubEnvironment);
Ajustado!

2021-06-17 22:44 UTC, vberardi commented
Testes adicionados!

2021-06-17 23:17 UTC, willian-soaresferreira approved these changes

2021-06-18 17:27 UTC, netorodrigues approved these changes

2021-06-21 21:59 UTC, merged