PAOPN-301 Hiding customer info from API
pagarme/ecommerce-module-core pull request #81
Opened 2023-02-15 18:43 UTC by RafaMelazzo

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-301](https://mundipagg.atlassian.net/browse/PAOPN-301)
| **What?**         | Hiding customer info from API
| **Why?**          | To hide sensitive information
| **How?**          | Using `preg_replace()` function to replace parts of the information with asterisk characters

2023-02-15 18:52 UTC, acedraz approved these changes

2023-02-15 21:00 UTC, fabiano-mallmann requested changes
Create a method to maintain the principle of single responsibility

2023-02-16 12:24 UTC, fabiano-mallmann approved these changes

2023-02-17 12:17 UTC, mauriciohaygert approved these changes

2023-02-17 13:27 UTC, merged